env:
  browser: true
  es2021: true
extends:
  - plugin:vue/essential
  - airbnb-base
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - vue
rules:
  max-len: off
  no-restricted-syntax: off
  no-continue: off
